------------------------------------------------------------
-- Consultas.sql                                           -
------------------------------------------------------------
-- Consultas no-triviales sobre la base de datos
-- de la empresa ficticia Transpórtate, a modo de prueba del
-- funcionamiento de la BD. 
--
-- Autor: Diego Villalpando
-- Mail:  diego.a.villalpando@ciencias.unam.mx
------------------------------------------------------------
