------------------------------------------------------------
-- DML.sql                                                 -
------------------------------------------------------------
-- Instrucciones para poblar BD. 
--
-- Autor: Diego Villalpando
-- Mail:  diego.a.villalpando@ciencias.unam.mx
------------------------------------------------------------
