------------------------------------------------------------
-- procedimientos_almacenados.sql                          -
------------------------------------------------------------
-- 5 Procedimientos almacenados para la BD documentados. 
--
-- Autor: Diego Villalpando
-- Mail:  diego.a.villalpando@ciencias.unam.mx
------------------------------------------------------------
